### ISSUE TITLE
The <s> token

### ISSUE THREAD

**Issue by Palipoor** [shmsw25/bart-closed-book-qa#1]
Hi,
In the [data.py](https://github.com/shmsw25/bart-closed-book-qa/blob/master/data.py) file, lines 87-88, what's the purpose of the <s> token prepended to texts?

**Comment by shmsw25** [comment]
Hi @Palipoor, thanks for your interest! It prepends `<s>` as a BOS (beginning-of-sentence) token for BART. In fact, `tokenizer.batch_encode_plus` also prepends `<s>`, so line 87-88 will actually make the sequence have two BOS tokens. We found that this enables the model to achieve a better performance for some reason (at least in our task; I am not sure if it is generic to any other task).

**Comment by Palipoor** [comment]
Thanks!
