### ISSUE TITLE
Broken link to results zip file?

### ISSUE THREAD

**Issue by idocal** [shmsw25/bart-closed-book-qa#3]
Hello, thank you for the open source code!
I am trying to download the best checkpoint from the provided link and apparently it is not available. Can you please provide a working link in order to perform some quality checks?

Thanks in advance!

**Comment by shmsw25** [comment]
Hi @idocal, thanks for your interest. I checked the link again but it seems to be working for me.
Would you check [this link](http://nlp.cs.washington.edu/ambigqa/models/nq-bart-closed-qa/nq-bart-closed-qa.zip) again? Thanks!

**Comment by idocal** [comment]
It now works, thanks! I guess it was a temporary issue.
