### ISSUE TITLE
Bart Model decoder_input_ids when training 

### ISSUE THREAD

**Issue by Liangtaiwan** [shmsw25/bart-closed-book-qa#4]
Hi,

I'm confused about the following section.
https://github.com/shmsw25/bart-closed-book-qa/blob/4373d0e5f8646833bef3e752a7e79b30d912e4e5/bart.py#L11-L15

This makes the decoder_input_ids from
```
<s>  This is an example <\s> <pad> ...
```
to 
```
<s > <s>  This is an example <\s> <pad> ...
```

I think what should we do is change the LM targets to 
```
This is an example <\s> <pad> ...
```

**Comment by shmsw25** [comment]
Hi @Liangtaiwan, thanks for your question. This is actually the input to the model, not the target. The model will be given
```
</s> <s> This is an example </s> <pad> ...
```
and outputs
```
<s> This is an example </a> <pad> <pad> ...
```

Let me know if this makes sense to you.

**Comment by Liangtaiwan** [comment]
Sorry for misleading.

I mean I think the inputs should be
```
<s> This is an example </a> <pad> <pad> ...
```

and outputs
```
This is an example </a> <pad> <pad> ...
```

It's weird for models to output SOS token.

**Comment by shmsw25** [comment]
Got it. I totally agree with you that these two options are conceptually the same, and generating `<s>` is redundant.

I should clarify that this is what HF codes does; in [_prepare_bart_decoder_inputs](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_bart.py#L148), they shift the sequence to the right by pre-pending `</s>` in the beginning. I believe this is the process that pretraining has gone through, and it is generally better to make fine-tuning similar to pretraining.

**Comment by Liangtaiwan** [comment]
I see. Thanks for your clarify.
