### ISSUE TITLE
RuntimeError: NCCL Error 2: unhandled system error

### ISSUE THREAD

**Issue by zhenyuhe00** [shmsw25/bart-closed-book-qa#8]
Hi,
Thank you for your nice code.
I ran your code with 8 Nvidia 2080ti GPUs and but this error occurred. Do you know anything about it?
Thanks in advance!

**Comment by shmsw25** [comment]
Hi @hzy-hzy, I'll take a look - do you have an error message?

**Comment by shmsw25** [comment]
Hi @hzy-hzy, sorry I am not aware of this error - the error seems to be a problem of pytorch and hardward mismatch, rather than this specific code. But looks like there're related discussions, including [this pytorch issue](https://github.com/pytorch/pytorch/issues/49095), which would help!

**Comment by zhenyuhe00** [comment]
That's very kind of you. Thanks!
